services:
  filmapi:
    build: 
      context: .
      dockerfile: filmapi.dockerfile
    depends_on:
      - pagiladb
    environment:
      - DB_HOSTNAME=pagiladb
    ports:
      - "8000:8000"
  pagiladb:
    build: 
      context: .
      dockerfile: pagiladb.dockerfile
    environment:
      - POSTGRES_DB=pagila
      - POSTGRES_PASSWORD=postgres